dict_gn = {
    "Arad": {"Zerid": 75, "Timisoara": 118, "Sibiu": 140},
    "Zerid": {"Oradea": 71, "Arad": 75},
    "Timisoara": {"Lugoj": 111, "Arad": 118},
    "Sibiu": {"Rimnicu Vilcea": 80, "Fagaras": 90, "Arad": 140, "Oradea": 151},
    "Oradea": {"Zerid": 71, "Sibiu": 151},
    "Lugoj": {"Mehadia": 70, "Timisoara": 111},
    "Rimnicu Vilcea": {
        "Sibiu": 80,
        "Pitesti": 97,
        "Craiova": 146,
    },
    "Fagaras": {"Sibiu": 99, "Bucharest": 211},
    "Mehadia": {"Lugoj": 70, "Drobeta": 75},
    "Pitesti": {
        "Rimnicu Vilcea": 97,
        "Bucharest": 101,
        "Craiova": 138,
    },
    "Craiova": {"Drobeta": 120, "Pitesti": 138, "Rimnicu Vilcea": 146},
    "Bucharest": {"Urziceni": 85, "Giurgiu": 90, "Pitesti": 101, "Fagaras": 211},
    "Drobeta": {"Mehadia": 75, "Craiova": 120},
    "Urziceni": {"Bucharest": 85, "Hirsova": 98, "Vaslui": 142},
    "Giurgiu": {"Bucharest": 90},
    "Hirsova": {"Eforie": 86, "Urziceni": 98},
    "vaslui": {"Iasi": 92, "Uziceni": 142},
    "Eforie": {"Hirsova": 86},
    "Iasi": {"Neamt": 87, "Vaslui": 92},
    "Neamt": {"Iasi": 87},
}
